"""Prepare controlled code and biomedical continuation data for Exp53."""

from __future__ import annotations

import argparse
import json
import re
from pathlib import Path
from typing import Any

from tqdm import tqdm

from .common import (
    BASE_MODEL_ID,
    BASE_REVISION,
    PERMISSIVE_CODE_LICENSES,
    approx_tokens,
    paths_for,
    text_hash,
    write_json,
)


def _lazy_imports():
    from datasets import load_dataset  # type: ignore
    from transformers import AutoTokenizer  # type: ignore

    return load_dataset, AutoTokenizer


def _norm_space(text: str) -> str:
    text = text.replace("\r\n", "\n").replace("\r", "\n")
    text = re.sub(r"\n{4,}", "\n\n\n", text)
    return text.strip()


def _code_text(row: dict[str, Any], *, max_chars: int) -> tuple[str | None, dict[str, Any]]:
    license_name = str(row.get("license", "")).lower().strip()
    if license_name not in PERMISSIVE_CODE_LICENSES:
        return None, {"skip": "license", "license": license_name}
    if bool(row.get("autogenerated")):
        return None, {"skip": "autogenerated"}
    content = _norm_space(str(row.get("content", "")))
    if len(content) < 500:
        return None, {"skip": "too_short"}
    content = content[:max_chars]
    path = str(row.get("path", "unknown.py"))
    repo = str(row.get("repo_name", "unknown_repo"))
    text = f"<file_sep>\n# repo: {repo}\n# path: {path}\n{content}\n"
    return text, {"license": license_name, "path": path, "repo": repo}


def _biomed_text(row: dict[str, Any], *, max_chars: int) -> tuple[str | None, dict[str, Any]]:
    metadata = row.get("metadata") or {}
    license_name = str(metadata.get("license", "")).lower()
    if "creative commons" not in license_name and "cc by" not in license_name and "cc0" not in license_name:
        return None, {"skip": "license", "license": license_name[:120]}
    text = _norm_space(str(row.get("text", "")))
    if len(text) < 1000:
        return None, {"skip": "too_short"}
    text = text[:max_chars]
    journal = str(metadata.get("journal", ""))
    article_id = str(row.get("id", "unknown_article"))
    out = f"<article_sep>\nArticle: {article_id}\nJournal: {journal}\n{text}\n"
    return out, {"license": license_name[:160], "article_id": article_id, "journal": journal}


def _record_for_support(
    *,
    domain: str,
    idx: int,
    text: str,
    tokenizer: Any,
    prefix_tokens: int,
    continuation_min_tokens: int,
    meta: dict[str, Any],
) -> dict[str, Any] | None:
    ids = tokenizer.encode(text, add_special_tokens=False)
    if len(ids) < prefix_tokens + continuation_min_tokens:
        return None
    prefix = tokenizer.decode(ids[:prefix_tokens], skip_special_tokens=False, clean_up_tokenization_spaces=False)
    category = "CONTENT-CODE" if domain == "code" else "CONTENT-BIOMED"
    return {
        "id": f"exp53_{domain}_{idx:05d}",
        "category": category,
        "source": f"exp53_{domain}_support",
        "prompt": prefix,
        "formats": {"B": prefix},
        "metadata": {"domain": domain, **meta},
    }


def prepare_domain(args: argparse.Namespace, domain: str) -> dict[str, Any]:
    load_dataset, AutoTokenizer = _lazy_imports()
    tokenizer = AutoTokenizer.from_pretrained(
        args.base_model,
        revision=args.base_revision,
        trust_remote_code=True,
        token=args.hf_token,
    )
    paths = paths_for(args.run_root, domain)
    paths.data_dir.mkdir(parents=True, exist_ok=True)
    for path in (paths.train_jsonl, paths.eval_jsonl, paths.support_jsonl):
        if path.exists() and not args.force:
            raise FileExistsError(f"{path} exists; pass --force to overwrite")
        if path.exists():
            path.unlink()

    if domain == "code":
        dataset_id = "codeparrot/codeparrot-clean"
        text_fn = _code_text
    elif domain == "biomed":
        dataset_id = "common-pile/pubmed"
        text_fn = _biomed_text
    else:
        raise ValueError(domain)

    stream = load_dataset(dataset_id, split="train", streaming=True)
    seen_hashes: set[str] = set()
    stats = {
        "domain": domain,
        "dataset_id": dataset_id,
        "train_approx_tokens_target": args.train_tokens,
        "train_approx_tokens_written": 0,
        "train_rows": 0,
        "eval_rows": 0,
        "support_rows": 0,
        "skips": {},
    }
    support_idx = 0
    with paths.train_jsonl.open("wb") as _:
        pass
    # Recreate via gzip/text helper after touching with binary-safe truncation.
    paths.train_jsonl.unlink(missing_ok=True)
    paths.eval_jsonl.unlink(missing_ok=True)
    paths.support_jsonl.unlink(missing_ok=True)

    from .common import append_jsonl

    pbar = tqdm(total=args.train_tokens, desc=f"prepare-{domain}", unit="tok")
    for row in stream:
        text, meta = text_fn(row, max_chars=args.max_chars)
        if text is None:
            reason = str(meta.get("skip", "unknown"))
            stats["skips"][reason] = int(stats["skips"].get(reason, 0)) + 1
            continue
        h = text_hash(text)
        if h in seen_hashes:
            stats["skips"]["duplicate"] = int(stats["skips"].get("duplicate", 0)) + 1
            continue
        seen_hashes.add(h)

        if stats["eval_rows"] < args.eval_records:
            append_jsonl(paths.eval_jsonl, {"text": text, "sha256": h, "metadata": meta})
            stats["eval_rows"] += 1
            continue
        if stats["support_rows"] < args.support_records:
            support = _record_for_support(
                domain=domain,
                idx=support_idx,
                text=text,
                tokenizer=tokenizer,
                prefix_tokens=args.support_prefix_tokens,
                continuation_min_tokens=args.support_continuation_min_tokens,
                meta=meta,
            )
            support_idx += 1
            if support is not None:
                append_jsonl(paths.support_jsonl, support)
                stats["support_rows"] += 1
                continue

        token_est = approx_tokens(text)
        append_jsonl(paths.train_jsonl, {"text": text, "sha256": h, "metadata": meta, "approx_tokens": token_est})
        stats["train_rows"] += 1
        stats["train_approx_tokens_written"] += token_est
        pbar.update(token_est)
        if stats["train_approx_tokens_written"] >= args.train_tokens:
            break
    pbar.close()

    stats["ok"] = (
        stats["train_approx_tokens_written"] >= args.train_tokens
        and stats["eval_rows"] >= args.eval_records
        and stats["support_rows"] >= args.support_records
    )
    write_json(paths.data_manifest, stats)
    if not stats["ok"]:
        raise RuntimeError(f"data preparation incomplete for {domain}: {json.dumps(stats, indent=2)}")
    return stats


def parse_args() -> argparse.Namespace:
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument("--run-root", type=Path, required=True)
    parser.add_argument("--domains", nargs="+", default=["code", "biomed"])
    parser.add_argument("--base-model", default=BASE_MODEL_ID)
    parser.add_argument("--base-revision", default=BASE_REVISION)
    parser.add_argument("--hf-token", default=None)
    parser.add_argument("--train-tokens", type=int, default=20_000_000)
    parser.add_argument("--eval-records", type=int, default=512)
    parser.add_argument("--support-records", type=int, default=600)
    parser.add_argument("--support-prefix-tokens", type=int, default=160)
    parser.add_argument("--support-continuation-min-tokens", type=int, default=64)
    parser.add_argument("--max-chars", type=int, default=64_000)
    parser.add_argument("--force", action="store_true")
    return parser.parse_args()


def main() -> None:
    args = parse_args()
    payload = {domain: prepare_domain(args, domain) for domain in args.domains}
    print(json.dumps(payload, indent=2, sort_keys=True))


if __name__ == "__main__":
    main()

