"""
Exp2 entry point: IC vs OOC vs R mechanistic data collection.

Usage:
    uv run python -m src.poc.exp02_ic_ooc_reasoning_mechanistic_comparison.run              # 8 GPUs (default)
    uv run python -m src.poc.exp02_ic_ooc_reasoning_mechanistic_comparison.run --gpus 1     # single GPU

Results are written to:
    results/exp02_ic_ooc_reasoning_mechanistic_comparison/{variant}_t{max_gen_tokens}/exp2_results.json
    results/exp02_ic_ooc_reasoning_mechanistic_comparison/{variant}_t{max_gen_tokens}/exp2_results.npz  (active_features)
    results/exp02_ic_ooc_reasoning_mechanistic_comparison/{variant}_t{max_gen_tokens}/plots/            (generated by run_plots)

Run plots separately:
    uv run python -m src.poc.exp02_ic_ooc_reasoning_mechanistic_comparison.run_plots
"""
import argparse

from src.poc.exp02_ic_ooc_reasoning_mechanistic_comparison.config import Exp2Config
from src.poc.exp02_ic_ooc_reasoning_mechanistic_comparison.prompts import PROMPTS
from src.poc.exp02_ic_ooc_reasoning_mechanistic_comparison.collect import collect_all, save_results


def main() -> None:
    parser = argparse.ArgumentParser(description="Exp2 data collection")
    parser.add_argument("--variant", choices=["pt", "it"], default="pt",
                        help="Model variant: 'pt' (pretrained base) or 'it' (instruction-tuned). "
                             "pt uses raw text completion; it applies the Gemma chat template.")
    parser.add_argument("--gpus", type=int, default=None,
                        help="Number of GPUs (overrides Exp2Config.n_gpus)")
    parser.add_argument("--no-chat-template", action="store_true", default=False,
                        help="Disable chat template for IT model (ablation: tests whether "
                             "δ-cosine patterns are weight-intrinsic or template-gated). "
                             "Output written to a separate _notmpl directory.")
    args = parser.parse_args()

    cfg = Exp2Config(model_variant=args.variant)
    if args.no_chat_template:
        import dataclasses
        cfg = dataclasses.replace(cfg, apply_chat_template=False)
    print(cfg)
    if args.gpus is not None:
        cfg.n_gpus = args.gpus

    n_prompts = sum(len(ps) for cat in PROMPTS.values() for ps in cat.values())

    print("=" * 60)
    print("Exp2: IC vs OOC vs R mechanistic comparison")
    print(f"  model   : {cfg.model_name}")
    print(f"  variant : {cfg.transcoder_variant}")
    print(f"  max_gen : {cfg.max_gen_tokens} tokens")
    print(f"  n_gpus  : {cfg.n_gpus}")
    print(f"  prompts : {n_prompts}")
    print(f"  output  : {cfg.output_path}")
    print("=" * 60)

    if cfg.n_gpus > 1:
        # Workers load the model independently — no main-process load needed.
        print(f"\n[1/3] Skipping main-process model load (each GPU worker loads independently)")
        loaded = None
    else:
        from src.poc.shared.model import load_model
        print("\n[1/3] Loading model + transcoders ...")
        loaded = load_model(cfg)

    print(f"\n[2/3] Collecting data across {cfg.n_gpus} GPU(s) ...")
    results, npz_data = collect_all(loaded, cfg, PROMPTS)

    print(f"\n[3/3] Saving {len(results)} results ...")
    save_results(results, npz_data, cfg)

    print("\nDone.")


if __name__ == "__main__":
    main()
