"""
Exp2 entry point: IC vs OOC vs R mechanistic data collection.

Usage:
    uv run python -m src.poc.exp2.run              # 8 GPUs (default)
    uv run python -m src.poc.exp2.run --gpus 1     # single GPU

Results are written to:
    results/exp2/{variant}_t{max_gen_tokens}/exp2_results.json
    results/exp2/{variant}_t{max_gen_tokens}/exp2_results.npz  (active_features)
    results/exp2/{variant}_t{max_gen_tokens}/plots/            (generated by run_plots)

Run plots separately:
    uv run python -m src.poc.exp2.run_plots
"""
import argparse

from src.poc.exp2.config import Exp2Config
from src.poc.exp2.prompts import PROMPTS
from src.poc.exp2.collect import collect_all, save_results


def main() -> None:
    parser = argparse.ArgumentParser(description="Exp2 data collection")
    parser.add_argument("--gpus", type=int, default=None,
                        help="Number of GPUs (overrides Exp2Config.n_gpus)")
    args = parser.parse_args()

    cfg = Exp2Config()
    if args.gpus is not None:
        cfg.n_gpus = args.gpus

    n_prompts = sum(len(ps) for cat in PROMPTS.values() for ps in cat.values())

    print("=" * 60)
    print("Exp2: IC vs OOC vs R mechanistic comparison")
    print(f"  model   : {cfg.model_name}")
    print(f"  variant : {cfg.transcoder_variant}")
    print(f"  max_gen : {cfg.max_gen_tokens} tokens")
    print(f"  n_gpus  : {cfg.n_gpus}")
    print(f"  prompts : {n_prompts}")
    print(f"  output  : {cfg.output_path}")
    print("=" * 60)

    if cfg.n_gpus > 1:
        # Workers load the model independently — no main-process load needed.
        print(f"\n[1/3] Skipping main-process model load (each GPU worker loads independently)")
        loaded = None
    else:
        from src.poc.shared.model import load_model
        print("\n[1/3] Loading model + transcoders ...")
        loaded = load_model(cfg)

    print(f"\n[2/3] Collecting data across {cfg.n_gpus} GPU(s) ...")
    results, npz_data = collect_all(loaded, cfg, PROMPTS)

    print(f"\n[3/3] Saving {len(results)} results ...")
    save_results(results, npz_data, cfg)

    print("\nDone.")


if __name__ == "__main__":
    main()
